language: java
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
install:
  - ./gradlew setupCiWorkspace
after_success:
  - curl -XPOST -H "Content-type: application/json" -d '{"status_message": "Failed", "branch": "$TRAVIS_BRANCH", "build_url": "https://travis-ci.org/Magneticraft-Team/Magneticraft/builds/$TRAVIS_BUILD_ID"}' 'http://2501.cypher.coffee:10000/travishook' 
#discord notifier
notifications:
  webhooks: http://2501.cypher.coffee:10000/travishook
