language: java
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
install:
  - exit 1
  - ./gradlew setupCiWorkspace
#discord notifier
notifications:
  webhooks:
    urls:
      - http://2501.cypher.coffee:10000/travishook
    on_success: never
    on_failure: always
